## Домашнее задание 1 (10 баллов)

Все задания ниже имеют равный вес (10/16).

### О задании

В этом домашнем задании вы попрактикуетесь в работе с библиотекой numpy, которая позволяет сравнительно легко и удобно выполнять разнообразные вычисления, избегая самостоятельной реализации поэлементной обработки.

- Вы впервые делаете ДЗ в таком формате, где нет автопроверок, как в Яндекс.Контесте. Здесь важно понимать, что не нужно стирать код, который уже прописан — его лишь нужно дополнить решениями по условиям задач.

- Во всех задачах необходимо написать код решения внутри функции и убедиться, что она работает, с помощью [assert](https://python-reference.readthedocs.io/en/latest/docs/statements/assert.html) на выражение с использованием этой функции для данных из условия. Начиная с 11 задачи никаких assert'ов нет.

- При решении задач запрещается использовать циклы (`for`, `while`) и оператор `if`. Да, `map`, `reduce`, `filter` и любые другие "чисто питоновские" конструкции тоже запрещены. **Используйте только функционал numpy**.

- Везде, где встречаются массивы или матрицы, подразумевается, что это `numpy.array`.

- **numpy reference:** https://numpy.org/doc/stable/reference/index.html

__Внимание!__ Домашнее задание выполняется самостоятельно. Не допускается помощь в решении домашнего задания от однокурсников или третьих лиц. «Похожие» решения считаются плагиатом, и все задействованные студенты — в том числе и те, у кого списали, — не могут получить за него больше 0 баллов.

Использование в решении домашнего задания генеративных моделей (ChatGPT и так далее) допускается исключительно в рамках справочной и образовательной информации. Любые другие случаи применения средств ИИ — например, для автоматической генерации кода по заданию — считаются плагиатом, и такое домашнее задание оценивается в 0 баллов.

В случае если в решении используются подходы, функции или формулы, не разбиравшиеся на лекциях и семинарах, — необходимо обязательное указание источника: ссылка на документацию, статью, другой ресурс. При отсутствии оформления источников задание может быть полностью обнулено.

In [328]:
import numpy as np

### Задание 1

Напишите функцию, возвращающую округленную взвешенную сумму оценок по данным оценкам и весам. Можете посчитать свою оценку за курс :) В нашем случае вес экзамена равен 0.3, вес домашек - 0.4, вес контрольной - 0.2, вес самостоятельных - 0.1. Например, если за экзамен у вас 7, за домашки 10, за контрольную 8, а за самостоятельные 6, то вы получите отличную оценку 8!

Обратите внимание, что на вход приходит всегда двумерный массив. В нем в каждой строке - окенки одного конкретного студента. От вас требуется вернуть итоговую оценку для всех студентов в массиве.

In [329]:
def result_mark(weights: np.array, marks: np.array) -> int:
    return np.round(marks @ weights).astype(int)

In [330]:
weights = np.array([0.3, 0.4, 0.2, 0.1])
marks = np.array([[7, 10, 8, 6], [6, 9, 7, 6]])

assert np.allclose(result_mark(weights, marks), np.array([8, 7]))

In [331]:
weights = np.array([0.3, 0.4, 0.2, 0.1])
marks = np.array([[7, 0, 8, 6]])

assert np.allclose(result_mark(weights, marks), np.array([4]))

### Задание 2

Напишите функцию, которая каждое четное число в массиве заменяет на его квадрат (вторую степень), а нечетное - на его синус. Округлите все значения в итоговом массиве до двух знаков после запятой.

In [332]:
def change_array(array: np.array) -> np.array:
  res = np.where(array % 2 == 0, array ** 2, np.sin(array))
  return np.round(res, 2)

In [333]:
array = np.array([2, 5, 1, 0, -6, 22, 213431])

assert np.allclose(change_array(array), np.array([4.0, -0.96, 0.84, 0.0, 36.0, 484.0, -0.58]))

In [334]:
array = np.array([3, 12, 15, -97, 6])

assert np.allclose(change_array(array), np.array([0.14, 144.0, 0.65, -0.38, 36.0]))

### Задание 3

Напишите функцию, которая вычисляет разность каждого элемента с предыдущим (для самого первого считайте, что его разница с "предыдущим" нулевая) в виде нового массива и возвращает вектор, в котором каждый новый элемент - сумма всех предыдущих из полученного нового массива.

In [335]:
def cumulative_sum_of_differences(array):
    diff = np.diff(array, prepend=array[0])
    return np.cumsum(diff)

In [336]:
array = np.array([3, 6, 2, 8])

assert np.allclose(cumulative_sum_of_differences(array), np.array([0, 3, -1, 5]))

In [337]:
array = np.array([5, 1])

assert np.allclose(cumulative_sum_of_differences(array), np.array([0, -4]))

https://numpy.org/doc/stable/reference/generated/numpy.diff.html

### Задание 4

Напишите функцию, которая транспонирует двумерный массив, затем делает из него одномерный (reshape), переводит все элементы массива в *int8* и выводит его отсортированным по убыванию.

In [338]:
def flatten_and_sort_transposed(array: np.array) -> np.array:
    tr = array.T.reshape(-1).astype(np.int8)
    return np.sort(tr)[::-1]


In [339]:
array = np.array([[256, -10], [-381, 112]])

assert np.allclose(flatten_and_sort_transposed(array), np.array([112, 0, -10, -125]))

In [340]:
array = np.array([[9, 8, 7], [3, 6, 129]])

assert np.allclose(flatten_and_sort_transposed(array), np.array([ 9, 8, 7, 6, 3, -127]))

### Задание 5

Напишите функцию, которая удаляет из массива все строки, среднее значение в которых больше общего среднего значения по всему массиву.

In [341]:
def filter_rows_by_mean(array):
    all = array.mean()
    row = array.mean(axis=1)
    return array[all >= row]

In [342]:
array = np.array([[1, 2, 3], [7, 8, 9], [4, 5, 6]])
res = filter_rows_by_mean(array)

assert res.ndim == 2
assert np.allclose(res, np.array([[1, 2, 3], [4, 5, 6]]))

In [343]:
array = np.array([[10, 20], [5, 5], [15, 15]])
res = filter_rows_by_mean(array)

assert res.ndim == 2
assert np.allclose(res, np.array([[5, 5]]))

### Задание 6

Напишите функцию, которая принимает на вход число - размер массива (квадратная матрица), который заполнен по принипу щахматной доски нулями и единицами. Первой (слева сверху) идет всегда единица. Напомним, что на шахматной доске белые и черные ячейки чередуются (в данном задании чередуются нули и единицы).

In [344]:
def create_checkerboard(number):
    return 1 - (np.indices((number, number)).sum(axis=0) % 2)

In [345]:
number = 3

assert np.allclose(create_checkerboard(number) - np.array([[1, 0, 1], [0, 1, 0], [1, 0, 1]]), np.zeros((number, number)))

In [346]:
number = 4

assert np.allclose(create_checkerboard(number) - np.array([[1, 0, 1, 0], [0, 1, 0, 1], [1, 0, 1, 0], [0, 1, 0, 1]]), np.zeros((number, number)))

https://numpy.org/doc/stable/reference/generated/numpy.indices.html

### Задание 7

Напишите функцию, которая соритрует строки двумерного массива по значению в первом (начиная с нуля) столбце (по возрастанию).

In [347]:
def sort_rows_by_second_column(array):
    return array[np.argsort(array[:, 1])]

In [348]:
array = np.array([[10, 2], [3, 5], [7, 1]])

assert np.allclose(sort_rows_by_second_column(array), np.array([[7, 1], [10, 2], [3, 5]]))

In [349]:
array = np.array([[5, 8, 1], [10, 3, 9], [2, 7, 0], [6, -1, 5]])

assert np.allclose(sort_rows_by_second_column(array), np.array([[6, -1, 5], [10, 3, 9], [2, 7, 0], [5, 8, 1]]))

https://numpy.org/doc/stable/reference/generated/numpy.argsort.html

### Задание 8

Напишите функцию, которая вычисляет сумму элементов [побочной](https://ru.wikipedia.org/wiki/Квадратная_матрица) диагонали квадратной матрицы.

In [350]:
def sum_counterdiagonal_elements(array):
    return np.trace(np.fliplr(array))

In [351]:
array = np.array([[5, 8, 1], [10, 3, 9], [2, 7, 0]])

assert sum_counterdiagonal_elements(array) == 6

In [352]:
array = np.array([[-4, -1, -1, 7], [6, -10, 5, -9], [3, -8, 6, 8], [-1, -6, 7, -10]])

assert sum_counterdiagonal_elements(array) == 3

https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html
https://numpy.org/doc/stable/reference/generated/numpy.fliplr.html

### Задание 9

Напишите функцию, которая принимает на вход три числа (начало отрезка, конец отрезка, количество точек на отрезке). Данная функция генерирует указанное количество точек равномерно на отрезке с указанными концами (точки равноудалены друг от друга). Затем функция генерирует другой массив - натуральный логарифм от всех точек отрезка плюс единица ($ln(point + 1)$). Возвращает функция массив пар точек вида (точка на отрезке, ее логарифм). Каждое значение в возвращаемом массиве должно быть округлено до двух знаков после запятой.

In [353]:
def generate_logarithm_points(start, end, count):
    pnt = np.linspace(start, end, count)
    logs = np.log(pnt + 1)
    return np.round(np.column_stack([pnt, logs]), 2)

In [354]:
start = 1
end = 10
count = 5

assert np.allclose(generate_logarithm_points(start, end, count), np.array([[1., 0.69], [3.25, 1.45], [5.5 , 1.87], [7.75, 2.17], [10., 2.4]]))

In [355]:
start = 5
end = 12
count = 4

assert np.allclose(generate_logarithm_points(start, end, count), np.array([[5., 1.79], [7.33, 2.12], [9.67, 2.37], [12., 2.56]]))

https://numpy.org/doc/stable/reference/generated/numpy.linspace.html

### Задание 10

Напишите функцию, которая нормализует входной двумерный массив.

Под нормализацией в данном задании подразумевается перевод всех чисел массива на отрезок $[0; 1]$. Очевидно, недостаточно просто вычесть/прибавить лишнее, чтобы остались числа на нужном отрезке. Суть нормализации массива в том, чтобы не потерять информацию о его элементах и их соотношениях. Потому, необходимо сохранить пропорции расстояний между каждым числом - спроецировать все точки на указанный отрезок. Такой метод масштабирования массива называется MinMaxScaling. Само название дает подсказку, как нужно решить задачу. Дробные числа округляйте до двух знаков после запятой.

*Будьте осторожны с делением...*

In [356]:
def min_max_scale(array):
    maxl = array.max()
    minl = array.min()
    norm = (array - minl) / (maxl - minl)
    return np.round(norm, 2)

In [357]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

assert np.allclose(min_max_scale(array), np.array([[0. , 0.12, 0.25], [0.38, 0.5 , 0.62], [0.75, 0.88, 1.]]))

In [358]:
array = np.array([[0, 1, 2], [3, 4, 5]])

assert np.allclose(min_max_scale(array), np.array([[0., 0.2, 0.4], [0.6, 0.8, 1.]]))

### Задание 11

Дано два массива: массив целых или нецелых чисел `celsius_temps`, представляющий собой температуру, измеренную в градусах Цельсия, в некотором регионе; и массив строковых данных `days`, представляющий собой набор тайтлов для дней, когда соответственно данная температура была зафиксирована.

Вам требуется написать функцию, возвращающую тайтлы тех дней, когда температура в Фаренгейтах была выше 90, а в Цельсиях — не ниже 30.

Формула для перевода температуры в Фаренгейты:
$$ F =  C * 9 / 5 + 32 $$
где:

* $F$ — температура в градусах Фаренгейта,
* $C$ — температура в градусах Цельсия.

In [359]:
def hot_days(celsius_temps, days):
  far = celsius_temps * 9 / 5 + 32
  return days[(90 < far) & (celsius_temps >= 30)]

In [360]:
celsius_temps = np.array([25, 32, 28, 35, 30])
days = np.array(['понедельник', 'вторник', 'среда', 'четверг', 'пятница'])

hot_days(celsius_temps, days)

array(['четверг'], dtype='<U11')

### Задание 12

На вход подается [трехмерный тензор](https://ru.wikipedia.org/wiki/%D0%A2%D0%B5%D0%BD%D0%B7%D0%BE%D1%80). Напишите функцию, которая для каждого слоя тензора выведет его верхний левый блок размера $2\times2$.

Например, для тензора:


```
                  [[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],

                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]],

                   [[19, 20, 21],
                    [22, 23, 24],
                    [25, 26, 27]]]
```

функция должна вывести:

```
                  [[[1, 2],
                    [4, 5]],

                   [[10, 11],
                    [13, 14]],

                   [[19, 20],
                    [22, 23]]]
```

In [361]:
def result(tensor):
  return tensor[:, :2, :2]

In [362]:
tensor = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],

                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]],

                   [[19, 20, 21],
                    [22, 23, 24],
                    [25, 26, 27]]])

result(tensor)

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]],

       [[19, 20],
        [22, 23]]])

### Задание 13

На вход подается двумерный массив с ценами акций различных компаний в разные дни: каждая строка — отдельный день; каждый столбец — отдельная компания.

Напишите функцию, которая:
* рассчитывает среднюю цену акций каждой компании за весь период;
* определяет компанию с наибольшей разницей между максимальной и минимальной ценой акций за весь период;
* находит такой день $t$, в который суммарное абсолютное изменение цен относительно предыдущего дня $t−1$ максимально.

In [363]:
def stats(stock_prices):
  mean = stock_prices.mean(axis = 0)

  compmx = stock_prices.max(axis=0) - stock_prices.min(axis=0)
  most_vol = np.argmax(compmx)

  changes = np.abs(np.diff(stock_prices, axis=0).sum(axis=1))
  t = np.argmax(changes) + 1
  return mean, most_vol, t


In [364]:
stock_prices = np.array([
    [110, 112, 108],
    [115, 118, 120],
    [108, 110, 105],
    [122, 121, 124],
    [128, 130, 125],
    [133, 132, 134],
    [129, 127, 130]
])

stats(stock_prices)

(array([120.71428571, 121.42857143, 120.85714286]), np.int64(2), np.int64(3))

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

### Задание 14

Напишите функцию, вычисляющую какую-нибудь первообразную данного полинома (в качестве константы возьмите ваше любимое число).

Например, если на вход поступает массив коэффициентов `array([4, 6, 0, 1])`, что соответствует полиному $4x^3 + 6x^2 + 1$, на выходе получается массив коэффициентов `array([1, 2, 0, 1, -2])`, соответствующий полиному $x^4 + 2x^3 + x - 2$.

В этом задании запрещено использовать функцию `polyint`, которая делает... буквально это!

In [365]:
def antiderivative(coefs):
    l = np.arange(len(coefs), 0, -1)
    d = coefs / l
    return np.concatenate([d, np.array([69])])


In [366]:
coefs = np.array([4, 6, 0, 1])
antiderivative(coefs)

array([ 1.,  2.,  0.,  1., 69.])

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

### Задание 15

Напишите функцию, которая принимает на вход вектор $v$, порог $t$ и $n$ случайных векторов $u_0, u_1, ...  u_n$ и возвращает индексы тех векторов $u_i$, [евклидово](https://ru.m.wikipedia.org/wiki/%D0%95%D0%B2%D0%BA%D0%BB%D0%B8%D0%B4%D0%BE%D0%B2%D0%B0_%D0%BC%D0%B5%D1%82%D1%80%D0%B8%D0%BA%D0%B0?from_mobile_app=true&mobile_internal_deeplink=true) расстояние которых до вектора $v$ не превышает порог $t$:

  $$ r_{euclidean}(v, u_i) \leq t$$




In [367]:
def r_euclidean_func_solution(v, n, t, u):
  l = np.linalg.norm(u - v, axis=1)
  return np.where(l <= t)[0]

In [368]:
v = np.array([1, 1, 1, 1])
n = 4
t = 1.0
u = np. array([[0, 0, 0, 0],
               [1, 0, 1, 0],
               [1, 1, 1, 1],
               [1, 1, 1, 0]])

r_euclidean_func_solution(v, n, t, u)

array([2, 3])

https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html

### Задание 16

Напишите функцию, вычисляющую [косинусную близость](https://en.wikipedia.org/wiki/Cosine_similarity) двух векторов.

Например, если на вход поступают вектора `array([-2, 1, 0, -5, 4, 3, -3])` и `array([0, 2, -2, 10, 6, 0, 0])`, ответом будет $-0.25$.

In [369]:
def cosine_similarity(vec1, vec2):
    n1 = np.linalg.norm(vec1)
    n2 = np.linalg.norm(vec2)
    res = np.dot(vec1, vec2) / (n1 * n2)
    return res

In [370]:
vec1 = np.array([-2, 1, 0, -5, 4, 3, -3])
vec2 = np.array([0, 2, -2, 10, 6, 0, 0])
cosine_similarity(vec1, vec2)

np.float64(-0.25)

https://numpy.org/doc/stable/reference/generated/numpy.dot.html